### ISSUE TITLE
compendium compatibility 

### ISSUE THREAD

**Issue by RubilaxXxx** [AirBurn0/am2playground#25]
when using TCL ArsMagica2.5 the compendium doesn't show any entry from your mod. (unlocked all entry using command)

tested on v11.4 & v 0.11.3

**Comment by AirBurn0** [comment]
> when using TCL ArsMagica2.5 the compendium doesn't show any entry from your mod. (unlocked all entry using command)
> 
> tested on v11.4 & v 0.11.3
When I checked everything worked.
Is there something about it in logs?

**Comment by AirBurn0** [comment]
Okie, I got to figure out what the hell is going on here:
Lets look on [ArcaneCompendium.init](https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/lore/ArcaneCompendium.java#L181) method:
```java
compendium.clear();
```
That's what caused this behaviour.
Well, like I said, AM2 usually inits compendium ONCE, and then calls [RegisterCompendiumEntries](https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/api/events/RegisterCompendiumEntries.java) event.

But [someone](https://github.com/TCLProject) [clearly does this more than once](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/java/am2/playerextensions/ExtendedProperties.java#L1322). IDK why this even needed. Maybe it's cool if i **change language** and then I'll get translated compendium without reloading entire game, but I still must create new world or  do some wierd stuff with compendium entries to achieve that.

**I do really hate how AM2 Compendium was made in comparsion with Thaumcraft Thaumonomicon**, if someone asks me.

So, since you seem to be the only living AM2.5 maintainer, I can see 3 ways to fix this:
1) You just need to insert [that line](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/java/am2/proxy/ClientProxy.java#L108):
`MinecraftForge.EVENT_BUS.post(new RegisterCompendiumEntries(ArcaneCompendium.instance))`
after [that line](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/java/am2/playerextensions/ExtendedProperties.java#L1322C3-L1322C102):
`ArcaneCompendium.instance.init(Minecraft.getMinecraft().getLanguageManager().getCurrentLanguage());`

2) Probably it's worth to **unfuck** this whole story about Compendium, and that's some good starting point.
I have already described the problem itself, all that remains is to figure out why all these methods were needed in the first place and rewrite all related code to something adequate. 
Well, the flag is in your hands.

3) We will not touch the broken AM2.5 code and I'll just make another core-mod that will fix everything again. Well, yes, ASM is that simple, huh. Please have mercy on me, that's the worst solution ever.

**Comment by RubilaxXxx** [comment]
yup, 

> You just need to insert [that line](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/java/am2/proxy/ClientProxy.java#L108):
MinecraftForge.EVENT_BUS.post(new RegisterCompendiumEntries(ArcaneCompendium.instance))
after [that line](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/java/am2/playerextensions/ExtendedProperties.java#L1322C3-L1322C102):
ArcaneCompendium.instance.init(Minecraft.getMinecraft().getLanguageManager().getCurrentLanguage());
And hope for problem solved.
>
that fixed it, will be in next release. 😄
